---
# handlers file for dnsmasq
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: restart network service
  shell: "ifdown --exclude=lo -a; sleep 1; ifup --exclude=lo -a"
